# Generated by Django 6.0.3 on 2026-04-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nro_departamento', models.IntegerField(unique=True)),
                ('nro_medicos', models.IntegerField(null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('email_departemento', models.EmailField(max_length=254)),
            ],
        ),
    ]
